name: macos-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:  
    runs-on: macos-latest
    
    defaults:
      run:
        shell: bash
        
    steps:
    - uses: actions/checkout@v2
    - name: install g++
      run: |
          brew install gcc
          sudo ln -sf $(ls -d /usr/local/bin/* | grep "/g++-" | sort -r | head -n1) /usr/local/bin/g++
          g++ --version
    - name: compile
      run: g++ -O2 -std=c++11 -fopenmp -mbmi2 -lpthread Excalibur.cpp loguru.cpp -o Excalibur -ldl
